#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EprojectWithWcf
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eproject")]
	public partial class DBConnectionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBConnectionDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["eprojectConnectionString3"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteInBrand")]
		public int DeleteInBrand([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> brand_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brand_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteIncatgory")]
		public int DeleteIncatgory([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteInProduct")]
		public int DeleteInProduct([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pro_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pro_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertInBrands")]
		public int insertInBrands([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string brandName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brandName, cat_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertIncatgory")]
		public int insertIncatgory([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cat_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertInProducts")]
		public int insertInProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="VarChar(50)")] string productName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductPrice", DbType="VarChar(50)")] string productPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductQuantity", DbType="VarChar(50)")] string productQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> brand_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productName, productPrice, productQuantity, brand_id, cat_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectfromSerchWise")]
		public ISingleResult<SelectfromSerchWiseResult> SelectfromSerchWise([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alpabeat", DbType="VarChar(100)")] string alpabeat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alpabeat);
			return ((ISingleResult<SelectfromSerchWiseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectInBrand")]
		public ISingleResult<SelectInBrandResult> SelectInBrand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectInBrandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectInBrandByCat")]
		public ISingleResult<SelectInBrandByCatResult> SelectInBrandByCat([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat_id);
			return ((ISingleResult<SelectInBrandByCatResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelectInProduct")]
		public ISingleResult<SelectInProductResult> SelectInProduct()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelectInProductResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SelecttIncatgory")]
		public ISingleResult<SelecttIncatgoryResult> SelecttIncatgory()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SelecttIncatgoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateInBrands")]
		public int UpdateInBrands([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> brand_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string brand_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brand_id, brand_name, cat_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateIncatgory")]
		public int UpdateIncatgory([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cat_name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cat_id, cat_name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateInProducts")]
		public int UpdateInProducts([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> product_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cat_id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductName", DbType="VarChar(50)")] string productName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductPrice", DbType="VarChar(50)")] string productPrice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductQuantity", DbType="VarChar(50)")] string productQuantity, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> brand_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), product_id, cat_id, productName, productPrice, productQuantity, brand_id);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SelectfromSerchWiseResult
	{
		
		private int _pro_id;
		
		private string _pro_name;
		
		private string _pro_price;
		
		private string _proQuantity;
		
		private string _brd_name;
		
		private string _cat_name;
		
		public SelectfromSerchWiseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this._pro_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_name
		{
			get
			{
				return this._pro_name;
			}
			set
			{
				if ((this._pro_name != value))
				{
					this._pro_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this._pro_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proQuantity", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string proQuantity
		{
			get
			{
				return this._proQuantity;
			}
			set
			{
				if ((this._proQuantity != value))
				{
					this._proQuantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brd_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string brd_name
		{
			get
			{
				return this._brd_name;
			}
			set
			{
				if ((this._brd_name != value))
				{
					this._brd_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_name
		{
			get
			{
				return this._cat_name;
			}
			set
			{
				if ((this._cat_name != value))
				{
					this._cat_name = value;
				}
			}
		}
	}
	
	public partial class SelectInBrandResult
	{
		
		private int _brd_id;
		
		private string _brd_name;
		
		private string _cat_name;
		
		private int _cat_id;
		
		public SelectInBrandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brd_id", DbType="Int NOT NULL")]
		public int brd_id
		{
			get
			{
				return this._brd_id;
			}
			set
			{
				if ((this._brd_id != value))
				{
					this._brd_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brd_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string brd_name
		{
			get
			{
				return this._brd_name;
			}
			set
			{
				if ((this._brd_name != value))
				{
					this._brd_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_name
		{
			get
			{
				return this._cat_name;
			}
			set
			{
				if ((this._cat_name != value))
				{
					this._cat_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int NOT NULL")]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this._cat_id = value;
				}
			}
		}
	}
	
	public partial class SelectInBrandByCatResult
	{
		
		private int _brd_id;
		
		private string _brd_name;
		
		private string _cat_name;
		
		public SelectInBrandByCatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brd_id", DbType="Int NOT NULL")]
		public int brd_id
		{
			get
			{
				return this._brd_id;
			}
			set
			{
				if ((this._brd_id != value))
				{
					this._brd_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brd_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string brd_name
		{
			get
			{
				return this._brd_name;
			}
			set
			{
				if ((this._brd_name != value))
				{
					this._brd_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_name
		{
			get
			{
				return this._cat_name;
			}
			set
			{
				if ((this._cat_name != value))
				{
					this._cat_name = value;
				}
			}
		}
	}
	
	public partial class SelectInProductResult
	{
		
		private int _pro_id;
		
		private string _pro_name;
		
		private string _pro_price;
		
		private string _proQuantity;
		
		private string _brd_name;
		
		private string _cat_name;
		
		public SelectInProductResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this._pro_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_name
		{
			get
			{
				return this._pro_name;
			}
			set
			{
				if ((this._pro_name != value))
				{
					this._pro_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this._pro_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proQuantity", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string proQuantity
		{
			get
			{
				return this._proQuantity;
			}
			set
			{
				if ((this._proQuantity != value))
				{
					this._proQuantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brd_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string brd_name
		{
			get
			{
				return this._brd_name;
			}
			set
			{
				if ((this._brd_name != value))
				{
					this._brd_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_name
		{
			get
			{
				return this._cat_name;
			}
			set
			{
				if ((this._cat_name != value))
				{
					this._cat_name = value;
				}
			}
		}
	}
	
	public partial class SelecttIncatgoryResult
	{
		
		private int _cat_id;
		
		private string _cat_name;
		
		public SelecttIncatgoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", DbType="Int NOT NULL")]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this._cat_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_name
		{
			get
			{
				return this._cat_name;
			}
			set
			{
				if ((this._cat_name != value))
				{
					this._cat_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
